<template><div><div class="page-heading"><div><p class="eyebrow">APPOINTMENTS</p><h1>预约与报告</h1><p class="muted">找到需要处理的预约，继续完成检查记录。</p></div><el-button @click="load" :loading="busy">刷新列表</el-button></div><div class="stat-row"><div class="stat-card"><span>筛选结果</span><strong>{{total}}<small> 条预约</small></strong></div><div class="stat-card"><span>工作流程</span><strong class="stat-text">查预约 → 填结果 → 归档</strong></div></div>
<section class="surface"><form class="filter-grid" @submit.prevent="search"><label>手机号<el-input v-model="filters.userId" placeholder="按手机号查询" clearable/></label><label>姓名<el-input v-model="filters.realName" placeholder="按姓名查询" clearable/></label><label>性别<el-select v-model="filters.sex" clearable placeholder="全部"><el-option label="男" :value="1"/><el-option label="女" :value="0"/></el-select></label><label>体检套餐<el-select v-model="filters.smId" clearable placeholder="全部套餐"><el-option v-for="s in meals" :key="s.smId" :label="s.name" :value="s.smId"/></el-select></label><label>体检日期<el-date-picker v-model="filters.orderDate" type="date" value-format="YYYY-MM-DD" placeholder="选择日期" style="width:100%"/></label><label>归档状态<el-select v-model="filters.state" clearable placeholder="全部状态"><el-option label="未归档" :value="1"/><el-option label="已归档" :value="2"/></el-select></label><div class="filter-actions"><el-button type="primary" native-type="submit">查询预约</el-button><el-button @click="reset">重置</el-button></div></form></section>
<section class="surface spaced"><div class="section-heading"><h2>预约记录</h2><span class="muted">共 {{total}} 条</span></div><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-table v-loading="busy" :data="rows" stripe empty-text="暂无符合条件的预约"><el-table-column prop="orderId" label="预约编号" width="100"/><el-table-column label="体检用户" min-width="140"><template #default="{row}"><strong>{{row.users.realName}}</strong><div class="muted">{{row.userId}}</div></template></el-table-column><el-table-column label="性别" width="70"><template #default="{row}">{{row.users.sex===1?'男':'女'}}</template></el-table-column><el-table-column prop="hospital.name" label="体检医院" min-width="170"/><el-table-column prop="setmeal.name" label="套餐" min-width="190"/><el-table-column prop="orderDate" label="体检日期" width="120"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.state===2?'success':'warning'">{{row.state===2?'已归档':'未归档'}}</el-tag></template></el-table-column><el-table-column label="操作" width="130" fixed="right"><template #default="{row}"><el-button size="small" type="primary" plain @click="router.push({path:'/ordersContent',query:{orderId:row.orderId}})">{{row.state===2?'查看报告':'录入结果'}}</el-button></template></el-table-column></el-table><el-pagination class="pagination" background layout="prev, pager, next" :page-size="filters.maxPageNum" :current-page="filters.pageNum" :total="total" @current-change="changePage"/></section></div></template>
<script setup>
import {ref,reactive,onMounted} from 'vue'
import {useRouter} from 'vue-router'
import {api} from '../api'
const router=useRouter(),rows=ref([]),meals=ref([]),total=ref(0),busy=ref(false),error=ref('')
const initial=()=>({userId:'',realName:'',sex:'',smId:'',orderDate:'',state:'',pageNum:1,maxPageNum:8})
const filters=reactive(initial());let version=0
async function load(){const id=++version;busy.value=true;error.value='';try{const r=await api.adminOrders({...filters});if(id===version){rows.value=r.list;total.value=r.total}}catch(e){if(id===version)error.value=e.message}finally{if(id===version)busy.value=false}}
function search(){filters.pageNum=1;load()}function reset(){Object.assign(filters,initial());load()}function changePage(p){filters.pageNum=p;load()}
onMounted(async()=>{await load();try{meals.value=await api.setmeals()}catch(e){error.value=e.message}})
</script>
